# Generated by Django 5.0.6 on 2024-06-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('l_code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('r_u', models.CharField(blank=True, max_length=1, null=True)),
                ('addr1', models.CharField(blank=True, max_length=100, null=True)),
                ('addr2', models.CharField(blank=True, max_length=200, null=True)),
                ('p_name', models.CharField(blank=True, max_length=100, null=True)),
                ('d_name', models.CharField(blank=True, max_length=100, null=True)),
                ('states', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
    ]
