# Generated by Django 5.0.6 on 2024-06-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sform', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('ref_data', models.BigIntegerField(primary_key=True, serialize=False)),
                ('c_code', models.IntegerField(blank=True, null=True)),
                ('c_name', models.CharField(blank=True, max_length=200, null=True)),
                ('l_name', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'college',
                'managed': False,
            },
        ),
    ]
