# Generated by Django 5.0.6 on 2024-06-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sform', '0003_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('acc_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ifsc', models.CharField(blank=True, max_length=11, null=True)),
                ('b_name', models.CharField(blank=True, max_length=200, null=True)),
                ('b_loc', models.CharField(blank=True, max_length=100, null=True)),
                ('b_addr', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'bank',
                'managed': False,
            },
        ),
    ]
